[build]
  command = "npm run build" # Or the command to build your React app
  publish = "dist"         # Directory to publish (where your built React app resides)

[dev]
  command = "npm start"     # Command to start your development server (optional)

[[redirects]]              # Example redirects (optional)
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]                # Example headers (optional)
  for = "/*"
    [headers.values]
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"
      Referrer-Policy = "same-origin"
